config/routes.rb
Rails.application.routes.draw do
  get "/tasks", to: "tasks#index", as: :all_tasks
  
  post "/tasks", to: "tasks#create"
  get "/tasks/new", to: "tasks#new", as: :new_task
  
  get "/tasks/:id", to: "tasks#show", as: :task

  get "/tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "/tasks/:id", to: "tasks#update"

  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to task_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<div class="container">
<h1>Show all tasks</h1>
  <ul>
    <% @tasks.each do |task|%>
      <br>
      <li>Task: <%= link_to task.title, task_path(task) %></li>
      <li> Task details: <%= link_to task.details, task_path(task) %></li>
      <%# <li><%= link_to task.completed, show_task_path(task) %>
    <% end %>
  </ul>
  <%= link_to "New task", new_task_path %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= render "form", task: @task %>
<%= link_to "All tasks", all_tasks_path %>

app/views/tasks/show.html.erb
<h1>Show task</h1>

<ul>
    <li>Title: <%= @task.title %></li>
    <li>Task details: <%= @task.details %></li>
    <li>Completed: <%= @task.completed %></li>
</ul>

<%= link_to "All tasks", all_tasks_path %>
<%= link_to "Delete",
  task_path(@task),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>